//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string Fullname { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_type { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual Type Type { get; set; }
    }
}
